-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 16:24:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema transportcompany
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transportcompany
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transportcompany` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `transportcompany` ;

-- -----------------------------------------------------
-- Table `transportcompany`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportcompany`.`clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(255) NULL DEFAULT NULL,
  `surnameCl` VARCHAR(255) NULL DEFAULT NULL,
  `nameCl` VARCHAR(255) NULL DEFAULT NULL,
  `patronymicCl` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transportcompany`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportcompany`.`roles` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `titleRole` VARCHAR(255) NULL DEFAULT NULL,
  `salary` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transportcompany`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportcompany`.`drivers` (
  `idDriver` INT NOT NULL AUTO_INCREMENT,
  `surnameDr` VARCHAR(255) NULL DEFAULT NULL,
  `nameDr` VARCHAR(255) NULL DEFAULT NULL,
  `patronymicDr` VARCHAR(255) NULL DEFAULT NULL,
  `birthDate` DATE NULL DEFAULT NULL,
  `experience` INT NULL DEFAULT NULL,
  `idRole` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDriver`),
  INDEX `idRole` (`idRole` ASC) VISIBLE,
  CONSTRAINT `drivers_ibfk_1`
    FOREIGN KEY (`idRole`)
    REFERENCES `transportcompany`.`roles` (`idRole`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transportcompany`.`employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportcompany`.`employers` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `surnameEmp` VARCHAR(255) NULL DEFAULT NULL,
  `nameEmp` VARCHAR(255) NULL DEFAULT NULL,
  `patronymicEmp` VARCHAR(255) NULL DEFAULT NULL,
  `birthDate` DATE NULL DEFAULT NULL,
  `idRole` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `idRole` (`idRole` ASC) VISIBLE,
  CONSTRAINT `employers_ibfk_1`
    FOREIGN KEY (`idRole`)
    REFERENCES `transportcompany`.`roles` (`idRole`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transportcompany`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportcompany`.`routes` (
  `idRoute` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `distance` FLOAT NULL DEFAULT NULL,
  `basePrice` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idRoute`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transportcompany`.`transportations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportcompany`.`transportations` (
  `idTransportation` INT NOT NULL AUTO_INCREMENT,
  `idRoute` INT NULL DEFAULT NULL,
  `idDriver` INT NULL DEFAULT NULL,
  `idClient` INT NULL DEFAULT NULL,
  `dateDispatch` DATE NULL DEFAULT NULL,
  `dateArrivals` DATE NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `responEmployeeId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTransportation`),
  INDEX `idRoute` (`idRoute` ASC) VISIBLE,
  INDEX `idDriver` (`idDriver` ASC) VISIBLE,
  INDEX `idClient` (`idClient` ASC) VISIBLE,
  INDEX `responEmployeeId` (`responEmployeeId` ASC) VISIBLE,
  CONSTRAINT `transportations_ibfk_1`
    FOREIGN KEY (`idRoute`)
    REFERENCES `transportcompany`.`routes` (`idRoute`),
  CONSTRAINT `transportations_ibfk_2`
    FOREIGN KEY (`idDriver`)
    REFERENCES `transportcompany`.`drivers` (`idDriver`),
  CONSTRAINT `transportations_ibfk_3`
    FOREIGN KEY (`idClient`)
    REFERENCES `transportcompany`.`clients` (`idClient`),
  CONSTRAINT `transportations_ibfk_4`
    FOREIGN KEY (`responEmployeeId`)
    REFERENCES `transportcompany`.`employers` (`idEmployee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
